### ISSUE TITLE
Software Description

### ISSUE THREAD

**Issue by CorwinBurton** [CorwinBurton/NetMap#5]
We need a general outline for the actual software architecture. We can be general and high level, for now.

**Comment by moecollins512** [comment]
All,

I’ve sent out google drive invite for the proposed Project Plan.  Let me know if you can’t gain access. 

Moe

**Comment by CorwinBurton** [comment]
The NetMap project shall deliver an application capable of representing networked devices and their associated connections and routes. The interface shall be capable of illustrating details of the network device, including distinct icons based on the device type, and shall offer additional information when prompted by user interaction.

The network information shall be imported from common network tools, such as Nmap and the BIND tool suite, and saved for retrieval. Additional features, such as live network updates, may be included at a later date.

**Comment by moecollins512** [comment]
Yea I am reviewing it


________________________________

**Comment by moecollins512** [comment]
Hello Guys,

I am Finally up to speed. This is what I got for you:

USER INTERFACE FOR NETMAP TECHNOLOGIES
On loading the application, an input box will appear where the user will be required to enter a sudo name for purposes of identification. A file button will be provided to help the user select the Nmap file to import. Once successfully loaded, the application will display all the devices listed in the Nmap file. When there are more devices than can be fully displayed, horizontal and vertical scroll bars appear signaling the scroll capabilities.
Each device will be assigned an appropriate icon such as a router icon for a router device, a computer icon for any computer device found on the Nmap file. Each of these devices will appear with a generated ID below it.
On selecting a device, a context menu will appear which will contain information including the device type, IP address, MAC address, Open Ports and other details such as the OS type, Manufacturer and network distance.
On clicking the close button, the application will prompt the user to save the file, either using the existing filename or another name of choice.

I am not able to edit the Google Doc and I am not sure where to place this information in the doc, also my name is spelled wrong on the Doc. My name is Abass Cisse

Thanks,

I will be up for the next 3 hrs if you need anything else




________________________________

**Comment by moecollins512** [comment]
I’ll send you another invite. 

I suggest you add what you believe needs to be added and submit it for your project plan submission in the assignment folder within UMUC. I’ve already added my project plan prior to you input due to me not knowing if you were adding anything. With that being said, please add your input well in advance or at least communicate your intent to add info close to the assignment due date and time.  I’m available for talks via gmail and Corwin setup another way to communicate as well. I can respond within 1-3 hrs normally. 

Apologies if I seem harsh or anything, but I have to ensure we’re all engaged and collectively progressing towards completing this project.

R,
Moe
